local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.1
      rolling_window: true
      always_send_full_costmap: true
      width: 10
      height: 10
      resolution: 0.05
      track_unknown_space: false

      footprint: "[[0.53, 0.37], [0.53, -0.37], [-0.53, -0.37], [-0.53, 0.37]]"
      footprint_padding: 0.05

      plugins: ["stvl_layer", "denoise_layer", "inflation_layer"]

      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 2.0
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        observation_persistence: 0.0
        max_obstacle_height: 1.5
        mark_threshold: 2
        unknown_threshold: 15
        update_footprint_enabled: true
        combination_method: 1
        obstacle_range: 5.0
        origin_z: 0.0
        publish_voxel_map: false
        transform_tolerance: 0.1
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /zed/zed_node/point_cloud/cloud_registered
          marking: true
          clearing: true
          obstacle_range: 5.0
          min_obstacle_height: 0.05
          max_obstacle_height: 1.5
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          filter: "voxel"
          voxel_min_points: 0
          clear_after_reading: true
          max_z: 6.0
          min_z: 0.35
          vertical_fov_angle: 1.22173
          vertical_fov_offset: 0.0
          horizontal_fov_angle: 1.9199
          decay_acceleration: 3.0
          model_type: 0

      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 3
        group_connectivity_type: 8

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 2.0
        inflation_radius: 0.6
        inflate_unknown: false
        inflate_around_unknown: false



controller_server:
  ros__parameters:
    controller_frequency: 20.0
    use_sim_time: false
    costmap_update_timeout: 0.1
    odom_topic: /odometry/local
    odom_duration: 0.3

    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker_plugins: ["progress_checker"]

    progress_checker:
      plugin: "nav2_controller::PoseProgressChecker"
      required_movement_radius: 0.05
      required_movement_angle: 0.1
      movement_time_allowance: 5.0

    # ======= 목표 자세(yaw): SimpleGoalChecker는 yaw를 봄 =======
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.2618   # 15deg (recovery/spin 없이 종료 안정성 ↑)
      stateful: true

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      time_steps: 60
      model_dt: 0.05
      batch_size: 1500
      iteration_count: 2

      motion_model: "DiffDrive"

      vx_std: 0.4
      vy_std: 0.0
      wz_std: 0.7

      vx_max: 0.7
      vx_min: 0.0
      vy_max: 0.0
      wz_max: 0.5

      ax_max: 1.0
      ax_min: -1.0
      ay_max: 0.0
      az_max: 1.0

      temperature: 0.6
      gamma: 0.015

      reset_period: 2.0
      regenerate_noises: true
      open_loop: false
      visualize: false

      TrajectoryValidator:
        plugin: "mppi::DefaultOptimalTrajectoryValidator"
        collision_lookahead_time: 3.0
        consider_footprint: true

      critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathFollowCritic"]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 2.0

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        threshold_to_consider: 1.0
        symmetric_yaw_tolerance: false

      ObstaclesCritic:
        enabled: true
        cost_power: 3
        repulsion_weight: 0.6
        critical_weight: 100.0
        consider_footprint: true
        collision_cost: 10000.0
        collision_margin_distance: 0.15
        near_goal_distance: 0.5
        inflation_radius: 0.6
        cost_scaling_factor: 2.0

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        offset_from_furthest: 14
        threshold_to_consider: 2.0

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.7, 0.0, 0.5]
    min_velocity: [0.0, 0.0, -0.5]
    max_accel: [1.0, 0.0, 1.0]
    max_decel: [-1.0, 0.0, -1.0]
    odom_topic: /odometry/local
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    enabled: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_nav"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.1
    source_timeout: 2.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    enable_stamped_cmd_vel: True  # False for Jazzy or older
    use_realtime_priority: false
    polygons: [ "PolygonSlow", "FootprintApproach"]
    PolygonSlow:
      type: "polygon"
      points: "[[0.42886, 0.355472], [0.42886, -0.355472], [-0.42886, -0.355472], [-0.42886, 0.355472]]"
      action_type: "slowdown"
      min_points: 3  # max_points: 3 for Humble
      slowdown_ratio: 0.3
      visualize: True
      polygon_pub_topic: "polygon_slowdown"
      enabled: True
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 2.0
      simulation_time_step: 0.02
      min_points: 6  # max_points: 5 for Humble
      visualize: False
      enabled: True
    observation_sources: ["pointcloud"]
    pointcloud:
      type: "pointcloud"
      topic: "/zed/zed_node/point_cloud/cloud_registered"
      transport_type: "raw"  # raw or/ with compression (zlib, draco, zstd)
      min_height: 0.05
      max_height: 1.2
      min_range: 0.2
      enabled: True

